name: dbt_snowflake_iceberg_sync
version: 0.4.2
config-version: 2

profile: dbt_snowflake_iceberg_sync

require-dbt-version: ">=1.10.0,<3.0.0"

macro-paths:
  - macros

clean-targets:
  - target
  - dbt_packages
