name: dbt_snowflake_iceberg_sync
version: 0.1.0
config-version: 2
require-dbt-version: [">=1.10.0", "<2.0.0"]

dispatch:
  - macro_namespace: dbt_snowflake_iceberg_sync
    search_order:
      - dbt_snowflake_iceberg_sync

models:
  dbt_snowflake_iceberg_sync:
    +enabled: false
